experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
  dataset: facebook_book
  top_k: 10
  evaluation:
    cutoffs: [10]
    simple_metrics: [nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.RBRS:
      meta:
        hyper_max_evals: 20
        hyper_opt_alg: tpe
        verbose: True
        save_recs: False
        validation_rate: 1
        validation_metric: nDCGRendle2020@10
      lr: [ loguniform, -9.210340372, -5.298317367 ]
      epochs: 200
      factors: 64
      batch_size: 64
      n_rules: 2
#      l_w: [ loguniform, -12.512925465, -8.30258509299 ]
      l_w: [ loguniform, -11.512925465, -2.30258509299 ]
      l_rc: 0.005
      eps: 1e-40
      seed: 123
      early_stopping:
        patience: 5
        mode: auto
        monitor: nDCGRendle2020@10
        verbose: True
